Docker 3
Otus-DevOps-2021-08/ScoutBert_microservices pull request #2
Opened 2021-11-26 00:12 UTC by ScoutBert

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Скачать образ MongoDB
docker pull mongo:latest

Собрать образы
docker build -t scoutberty/post:1.0 ./post-py
docker build -t scoutberty/comment:1.0 ./comment
docker build -t scoutberty/ui:1.0 ./ui

Создать спец сеть
docker network create reddit

запустить контейнеры
docker run -d --network=reddit --network-alias=post_db --network-alias=comment_db mongo:latest
docker run -d --network=reddit --network-alias=post scoutberty/post:1.0
docker run -d --network=reddit --network-alias=comment scoutberty/comment:1.0
docker run -d --network=reddit -p 9292:9292 scoutberty/ui:1.0

Создадm Docker volume:
docker volume create reddit_db

Удалить старые копии контейнеров
docker kill $(docker ps -q)

Запустить контейнеры с volume
docker run -d --network=reddit --network-alias=post_db --network-alias=comment_db -v reddit_db:/data/db mongo:latest
docker run -d --network=reddit --network-alias=post scoutberty/post:1.0
docker run -d --network=reddit --network-alias=comment scoutberty/comment:1.0
docker run -d --network=reddit -p 9292:9292 scoutberty/ui:2.0

2021-11-26 00:14 UTC, ScoutBert commented
Подскажите с чем может быть связана проблема
  ×  docker: Check docker build & run (1 failed)
       ×  HTTP GET on http://post:5000/healthcheck body

2021-11-26 07:17 UTC, mrgreyves requested changes
Здравствуйте!)
Ошибка в тестах может быть связана с тем что при запросе хелсчека у сервиса пост, хелсчек не отдается, нужно посмотреть в чем там проблема, думаю проверки логов поста будет достаточно =)

2021-11-26 15:39 UTC, ScoutBert commented
Теперь, ок, спасибо

2021-11-28 19:05 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз. Все ваши описания команд думаю стоит вынести в ридми, если что там их "подсмотреть" будет гораздо удобнее =)

2021-11-28 19:34 UTC, merged